import { CatchAsyncError } from '../helpers/catchAsyncError.helpers.js'
import { APIResponse } from '../shared/apiResponse.shared.js'

export const getAllTasks = CatchAsyncError(async (request, response, next) => {})

